using System.Collections.Generic;

namespace Celeste.Mod.SJArchipelago.Items;



public static class EntityHandler
{
    public enum Items {
        IntroCrushers,
        Springs,
        TrafficBlocks,
        DashCrystals,
        DoubleDashCrystals,
        CassetteBlocks,
        DreamBlocks,
        StrawberrySeeds,
        Coins,
        SinkingPlatforms,
        MovingPlatforms,
        BlueClouds,
        PinkClouds,
        GreenBubbles,
        RedBubbles,
        MoveBlocks,
        WhiteBlock,
        SwapBlocks,
        DashSwitch,
        Seekers,
        TheoCrystals,
        Feathers,
        Kevins,
        Bumpers,
        BadelineOrbs,
        CoreBlocks,
        Iceballs,
        CoreSwitches,
        Pufferfish,
        Jellyfish,
        PowerBoxes,
        Birds,
        CrystalBombs,
        
        DreamDashCrystals,
        CerealBlockBumps,
        CerealBlockClouds,
        DashTrafficBlocks,
        BlueSprings,
        BlueBubbles,
        CassetteZippers,
        SingleJumpCrystals,
        TripleJumpCrystals,
        GravityTriggers,
        BlueTimeCrystals,
        GrayTimeCrystals,
        DashCrystalShards,
        TinyStrawberries,
        Roses,
        Pipes,
        TeleportFields,
        Ziplines,
        DashToggleBlocks,
        PurpleBubbles,
        DashSprings,
        PlatformJellyfish,
        GrayBooster,
        Skateboard,
        Umbrella,
        FakeHearts,
        WormholeBoosters,
        Portals,
    };
}