using System.Collections.Generic;

namespace Celeste.Mod.SJArchipelago.Items;



public static class EntityHandler
{
    public enum Items {
        IntroCrushers,
        Springs,
        TrafficBlocks,
        DashCrystals,
        DoubleDashCrystals,
        BlueCassetteBlock,
        PinkCassetteBlock,
        YellowCassetteBlock,
        GreenCassetteBlock,
        DreamBlocks,
        StrawberrySeeds,
        Coins,
        SinkingPlatforms,
        MovingPlatforms,
        BlueClouds,
        PinkClouds,
        GreenBubbles,
        RedBubbles,
        MoveBlocks,
        WhiteBlock,
        SwapBlocks,
        DashSwitch,
        Seekers,
        TheoCrystals,
        Feathers,
        Kevins,
        Bumpers,
        BadelineOrbs,
        CoreBlocks,
        Iceballs,
        CoreSwitches,
        Pufferfish,
        Jellyfish,
        PowerBoxes,
        Birds,
        CrystalBombs,
        
        DreamDashCrystals,
        CerealBlockBumps,
        CerealBlockClouds,
        DashTrafficBlocks,
        BlueSprings,
        BlueBubbles,
        CassetteZippers,
        SingleJumpCrystals,
        TripleJumpCrystals,
        GravityTriggers,
        TimeCrystals,
        DashCrystalShards,
        TinyStrawberries,
        Roses,
        Pipes,
        TeleportFields,
        Ziplines,
        DashToggleBlocks,
        PurpleBubbles,
        DashSprings,
    };
    public static Dictionary<int, string> IdToString = new Dictionary<int, string>()
    {
        {0x000, "Springs"},
        {0x001, "Traffic Blocks"},
        {0x002, "Dash Refills"},
        {0x003, "Double Dash Refills"},
        {0x004, "Blue Cassette Blocks"},
        {0x005, "Red Cassette Blocks"},
        {0x006, "Yellow Cassette Blocks"},
        {0x007, "Green Cassette Blocks"},
        {0x008, "Dream Blocks"},
        {0x009, "Strawberry Seeds"},
        {0x00A, "Coins"},
        {0x00B, "Sinking Platforms"},
        {0x00C, "Moving Platforms"},
        {0x00D, "Blue Clouds"},
        {0x00E, "Pink Clouds"},
        {0x00F, "Green Bubbles"},
        {0x010, "Red Bubbles"},
        {0x011, "Move Blocks"},
        {0x012, "White Block"},
        {0x013, "Swap Blocks"},
        {0x014, "Seekers"},
        {0x015, "Theo Crystals"},
        {0x016, "Feathers"},
        {0x017, "Kevins"},
        {0x018, "Bumpers"},
        {0x019, "Badeline Orbs"},
        {0x01A, "Core Blocks"},
        {0x01B, "Iceballs"},
        {0x01C, "Core Switches"},
        {0x01D, "Pufferfish"},
        {0x01E, "Jellyfish"},
        {0x01F, "Breaker Boxes"},
        {0x020, "Birds"},
    };
}